from typing import Dict
from pydantic import BaseModel

class CountryInDB(BaseModel):
    id:int
    name:str

database_country_name = Dict[str, CountryInDB]
database_country = Dict[int, CountryInDB]

database_country = {
    1:CountryInDB(**{1:"Afghanistan"}),
    2:CountryInDB(**{2:"Albania"}),
    3:CountryInDB(**{3:"Algeria"}),
    4:CountryInDB(**{4:"American Samoa"}),
    5:CountryInDB(**{5:"Andorra"}),
    6:CountryInDB(**{6:"Angola"}),
    7:CountryInDB(**{7:"Anguilla"}),
    8:CountryInDB(**{8:"Antarctica"}),
    9:CountryInDB(**{9:"Antigua and Barbuda"}),
    10:CountryInDB(**{10:"Argentina"}),
    11:CountryInDB(**{11:"Armenia"}),
    12:CountryInDB(**{12:"Aruba"}),
    13:CountryInDB(**{13:"Australia"}),
    14:CountryInDB(**{14:"Austria"}),
    15:CountryInDB(**{15:"Azerbaijan"}),
    16:CountryInDB(**{16:"Bahamas"}),
    17:CountryInDB(**{17:"Bahrain"}),
    18:CountryInDB(**{18:"Bangladesh"}),
    19:CountryInDB(**{19:"Barbados"}),
    20:CountryInDB(**{20:"Belarus"}),
    21:CountryInDB(**{21:"Belgium"}),
    22:CountryInDB(**{22:"Belize"}),
    23:CountryInDB(**{23:"Benin"}),
    24:CountryInDB(**{24:"Bermuda"}),
    25:CountryInDB(**{25:"Bhutan"}),
    26:CountryInDB(**{26:"Bolivia"}),
    27:CountryInDB(**{27:"Bosnia and Herzegovina"}),
    28:CountryInDB(**{28:"Botswana"}),
    29:CountryInDB(**{29:"Bouvet Island"}),
    30:CountryInDB(**{30:"Brazil"}),
    31:CountryInDB(**{31:"British Indian Ocean Territory"}),
    32:CountryInDB(**{32:"Brunei"}),
    33:CountryInDB(**{33:"Bulgaria"}),
    34:CountryInDB(**{34:"Burkina Faso"}),
    35:CountryInDB(**{35:"Burundi"}),
    36:CountryInDB(**{36:"Cambodia"}),
    37:CountryInDB(**{37:"Cameroon"}),
    38:CountryInDB(**{38:"Canada"}),
    39:CountryInDB(**{39:"Cape Verde"}),
    40:CountryInDB(**{40:"Cayman Islands"}),
    41:CountryInDB(**{41:"Central African Republic"}),
    42:CountryInDB(**{42:"Chad"}),
    43:CountryInDB(**{43:"Chile"}),
    44:CountryInDB(**{44:"China"}),
    45:CountryInDB(**{45:"Christmas Island"}),
    46:CountryInDB(**{46:"Cocos Keeling) Islands"}),
    47:CountryInDB(**{47:"Colombia"}),
    48:CountryInDB(**{48:"Comoros"}),
    49:CountryInDB(**{49:"Congo"}),
    50:CountryInDB(**{50:"Congo"}),
    51:CountryInDB(**{51:"Cook Islands"}),
    52:CountryInDB(**{52:"Costa Rica"}),
    53:CountryInDB(**{53:"Côte dIvoire"}),
    54:CountryInDB(**{54:"Croatia"}),
    55:CountryInDB(**{55:"Cuba"}),
    56:CountryInDB(**{56:"Cyprus"}),
    57:CountryInDB(**{57:"Czech Republic"}),
    58:CountryInDB(**{58:"Denmark"}),
    59:CountryInDB(**{59:"Djibouti"}),
    60:CountryInDB(**{60:"Dominica"}),
    61:CountryInDB(**{61:"Dominican Republic"}),
    62:CountryInDB(**{62:"East Timor"}),
    63:CountryInDB(**{63:"Ecuador"}),
    64:CountryInDB(**{64:"Egypt"}),
    65:CountryInDB(**{65:"El Salvador"}),
    66:CountryInDB(**{66:"Equatorial Guinea"}),
    67:CountryInDB(**{67:"Eritrea"}),
    68:CountryInDB(**{68:"Estonia"}),
    69:CountryInDB(**{69:"Ethiopia"}),
    70:CountryInDB(**{70:"Falkland Islands"}),
    71:CountryInDB(**{71:"Faroe Islands"}),
    72:CountryInDB(**{72:"Fiji Islands"}),
    73:CountryInDB(**{73:"Finland"}),
    74:CountryInDB(**{74:"France"}),
    75:CountryInDB(**{75:"French Guiana"}),
    76:CountryInDB(**{76:"French Polynesia"}),
    77:CountryInDB(**{77:"French Southern territories"}),
    78:CountryInDB(**{78:"Gabon"}),
    79:CountryInDB(**{79:"Gambia"}),
    80:CountryInDB(**{80:"Georgia"}),
    81:CountryInDB(**{81:"Germany"}),
    82:CountryInDB(**{82:"Ghana"}),
    83:CountryInDB(**{83:"Gibraltar"}),
    84:CountryInDB(**{84:"Greece"}),
    85:CountryInDB(**{85:"Greenland"}),
    86:CountryInDB(**{86:"Grenada"}),
    87:CountryInDB(**{87:"Guadeloupe"}),
    88:CountryInDB(**{88:"Guam"}),
    89:CountryInDB(**{89:"Guatemala"}),
    90:CountryInDB(**{90:"Guinea"}),
    91:CountryInDB(**{91:"Guinea-Bissau"}),
    92:CountryInDB(**{92:"Guyana"}),
    93:CountryInDB(**{93:"Haiti"}),
    94:CountryInDB(**{94:"Heard Island and McDonald Islands"}),
    95:CountryInDB(**{95:"Holy See Vatican City State)"}),
    96:CountryInDB(**{96:"Honduras"}),
    97:CountryInDB(**{97:"Hong Kong"}),
    98:CountryInDB(**{98:"Hungary"}),
    99:CountryInDB(**{99:"Iceland"}),
    100:CountryInDB(**{100:"India"}),
    101:CountryInDB(**{101:"Indonesia"}),
    102:CountryInDB(**{102:"Iran"}),
    103:CountryInDB(**{103:"Iraq"}),
    104:CountryInDB(**{104:"Ireland"}),
    105:CountryInDB(**{105:"Israel"}),
    106:CountryInDB(**{106:"Italy"}),
    107:CountryInDB(**{107:"Jamaica"}),
    108:CountryInDB(**{108:"Japan"}),
    109:CountryInDB(**{109:"Jordan"}),
    110:CountryInDB(**{110:"Kazakstan"}),
    111:CountryInDB(**{111:"Kenya"}),
    112:CountryInDB(**{112:"Kiribati"}),
    113:CountryInDB(**{113:"Kuwait"}),
    114:CountryInDB(**{114:"Kyrgyzstan"}),
    115:CountryInDB(**{115:"Laos"}),
    116:CountryInDB(**{116:"Latvia"}),
    117:CountryInDB(**{117:"Lebanon"}),
    118:CountryInDB(**{118:"Lesotho"}),
    119:CountryInDB(**{119:"Liberia"}),
    120:CountryInDB(**{120:"Libyan Arab Jamahiriya"}),
    121:CountryInDB(**{121:"Liechtenstein"}),
    122:CountryInDB(**{122:"Lithuania"}),
    123:CountryInDB(**{123:"Luxembourg"}),
    124:CountryInDB(**{124:"Macao"}),
    125:CountryInDB(**{125:"Macedonia"}),
    126:CountryInDB(**{126:"Madagascar"}),
    127:CountryInDB(**{127:"Malawi"}),
    128:CountryInDB(**{128:"Malaysia"}),
    129:CountryInDB(**{129:"Maldives"}),
    130:CountryInDB(**{130:"Mali"}),
    131:CountryInDB(**{131:"Malta"}),
    132:CountryInDB(**{132:"Marshall Islands"}),
    133:CountryInDB(**{133:"Martinique"}),
    134:CountryInDB(**{134:"Mauritania"}),
    135:CountryInDB(**{135:"Mauritius"}),
    136:CountryInDB(**{136:"Mayotte"}),
    137:CountryInDB(**{137:"Mexico"}),
    138:CountryInDB(**{138:"Micronesia"}),
    139:CountryInDB(**{139:"Moldova"}),
    140:CountryInDB(**{140:"Monaco"}),
    141:CountryInDB(**{141:"Mongolia"}),
    142:CountryInDB(**{142:"Montserrat"}),
    143:CountryInDB(**{143:"Morocco"}),
    144:CountryInDB(**{144:"Mozambique"}),
    145:CountryInDB(**{145:"Myanmar"}),
    146:CountryInDB(**{146:"Namibia"}),
    147:CountryInDB(**{147:"Nauru"}),
    148:CountryInDB(**{148:"Nepal"}),
    149:CountryInDB(**{149:"Netherlands"}),
    150:CountryInDB(**{150:"Netherlands Antilles"}),
    151:CountryInDB(**{151:"New Caledonia"}),
    152:CountryInDB(**{152:"New Zealand"}),
    153:CountryInDB(**{153:"Nicaragua"}),
    154:CountryInDB(**{154:"Niger"}),
    155:CountryInDB(**{155:"Nigeria"}),
    156:CountryInDB(**{156:"Niue"}),
    157:CountryInDB(**{157:"Norfolk Island"}),
    158:CountryInDB(**{158:"North Korea"}),
    159:CountryInDB(**{159:"Northern Mariana Islands"}),
    160:CountryInDB(**{160:"Norway"}),
    161:CountryInDB(**{161:"Oman"}),
    162:CountryInDB(**{162:"Pakistan"}),
    163:CountryInDB(**{163:"Palau"}),
    164:CountryInDB(**{164:"Palestine"}),
    165:CountryInDB(**{165:"Panama"}),
    166:CountryInDB(**{166:"Papua New Guinea"}),
    167:CountryInDB(**{167:"Paraguay"}),
    168:CountryInDB(**{168:"Peru"}),
    169:CountryInDB(**{169:"Philippines"}),
    170:CountryInDB(**{170:"Pitcairn"}),
    171:CountryInDB(**{171:"Poland"}),
    172:CountryInDB(**{172:"Portugal"}),
    173:CountryInDB(**{173:"Puerto Rico"}),
    174:CountryInDB(**{174:"Qatar"}),
    175:CountryInDB(**{175:"Réunion"}),
    176:CountryInDB(**{176:"Romania"}),
    177:CountryInDB(**{177:"Russian Federation"}),
    178:CountryInDB(**{178:"Rwanda"}),
    179:CountryInDB(**{179:"Saint Helena"}),
    180:CountryInDB(**{180:"Saint Kitts and Nevis"}),
    181:CountryInDB(**{181:"Saint Lucia"}),
    182:CountryInDB(**{182:"Saint Pierre and Miquelon"}),
    183:CountryInDB(**{183:"Saint Vincent and the Grenadines"}),
    184:CountryInDB(**{184:"Samoa"}),
    185:CountryInDB(**{185:"San Marino"}),
    186:CountryInDB(**{186:"Sao Tome and Principe"}),
    187:CountryInDB(**{187:"Saudi Arabia"}),
    188:CountryInDB(**{188:"Senegal"}),
    189:CountryInDB(**{189:"Seychelles"}),
    190:CountryInDB(**{190:"Sierra Leone"}),
    191:CountryInDB(**{191:"Singapore"}),
    192:CountryInDB(**{192:"Slovakia"}),
    193:CountryInDB(**{193:"Slovenia"}),
    194:CountryInDB(**{194:"Solomon Islands"}),
    195:CountryInDB(**{195:"Somalia"}),
    196:CountryInDB(**{196:"South Africa"}),
    197:CountryInDB(**{197:"South Georgia and the South Sandwich Islands"}),
    198:CountryInDB(**{198:"South Korea"}),
    199:CountryInDB(**{199:"Spain"}),
    200:CountryInDB(**{200:"Sri Lanka"}),
    201:CountryInDB(**{201:"Sudan"}),
    202:CountryInDB(**{202:"Suriname"}),
    203:CountryInDB(**{203:"Svalbard and Jan Mayen"}),
    204:CountryInDB(**{204:"Swaziland"}),
    205:CountryInDB(**{205:"Sweden"}),
    206:CountryInDB(**{206:"Switzerland"}),
    207:CountryInDB(**{207:"Syria"}),
    208:CountryInDB(**{208:"Taiwan"}),
    209:CountryInDB(**{209:"Tajikistan"}),
    210:CountryInDB(**{210:"Tanzania"}),
    211:CountryInDB(**{211:"Thailand"}),
    212:CountryInDB(**{212:"Togo"}),
    213:CountryInDB(**{213:"Tokelau"}),
    214:CountryInDB(**{214:"Tonga"}),
    215:CountryInDB(**{215:"Trinidad and Tobago"}),
    216:CountryInDB(**{216:"Tunisia"}),
    217:CountryInDB(**{217:"Turkey"}),
    218:CountryInDB(**{218:"Turkmenistan"}),
    219:CountryInDB(**{219:"Turks and Caicos Islands"}),
    220:CountryInDB(**{220:"Tuvalu"}),
    221:CountryInDB(**{221:"Uganda"}),
    222:CountryInDB(**{222:"Ukraine"}),
    223:CountryInDB(**{223:"United Arab Emirates"}),
    224:CountryInDB(**{224:"United Kingdom"}),
    225:CountryInDB(**{225:"United States"}),
    226:CountryInDB(**{226:"United States Minor Outlying Islands"}),
    227:CountryInDB(**{227:"Uruguay"}),
    228:CountryInDB(**{228:"Uzbekistan"}),
    229:CountryInDB(**{229:"Vanuatu"}),
    230:CountryInDB(**{230:"Venezuela"}),
    231:CountryInDB(**{231:"Vietnam"}),
    232:CountryInDB(**{232:"Virgin Islands"}),
    233:CountryInDB(**{233:"Virgin Islands"}),
    234:CountryInDB(**{234:"Wallis and Futuna"}),
    235:CountryInDB(**{235:"Western Sahara"}),
    236:CountryInDB(**{236:"Yemen"}),
    237:CountryInDB(**{237:"Yugoslavia"}),
    238:CountryInDB(**{238:"Zambia"}),
    239:CountryInDB(**{239:"Zimbabwe"})
}

database_country_name = {
    "Afghanistan":CountryInDB(**{1:"Afghanistan"}),
    "Albania":CountryInDB(**{2:"Albania"}),
    "Algeria":CountryInDB(**{3:"Algeria"}),
    "American Samoa":CountryInDB(**{4:"American Samoa"}),
    "Andorra":CountryInDB(**{5:"Andorra"}),
    "Angola":CountryInDB(**{6:"Angola"}),
    "Anguilla":CountryInDB(**{7:"Anguilla"}),
    "Antarctica":CountryInDB(**{8:"Antarctica"}),
    "Antigua and Barbuda":CountryInDB(**{9:"Antigua and Barbuda"}),
    "Argentina":CountryInDB(**{10:"Argentina"}),
    "Armenia":CountryInDB(**{11:"Armenia"}),
    "Aruba":CountryInDB(**{12:"Aruba"}),
    "Australia":CountryInDB(**{13:"Australia"}),
    "Austria":CountryInDB(**{14:"Austria"}),
    "Azerbaijan":CountryInDB(**{15:"Azerbaijan"}),
    "Bahamas":CountryInDB(**{16:"Bahamas"}),
    "Bahrain":CountryInDB(**{17:"Bahrain"}),
    "Bangladesh":CountryInDB(**{18:"Bangladesh"}),
    "Barbados":CountryInDB(**{19:"Barbados"}),
    "Belarus":CountryInDB(**{20:"Belarus"}),
    "Belgium":CountryInDB(**{21:"Belgium"}),
    "Belize":CountryInDB(**{22:"Belize"}),
    "Benin":CountryInDB(**{23:"Benin"}),
    "Bermuda":CountryInDB(**{24:"Bermuda"}),
    "Bhutan":CountryInDB(**{25:"Bhutan"}),
    "Bolivia":CountryInDB(**{26:"Bolivia"}),
    "Bosnia and Herzegovina":CountryInDB(**{27:"Bosnia and Herzegovina"}),
    "Botswana":CountryInDB(**{28:"Botswana"}),
    "Bouvet Island":CountryInDB(**{29:"Bouvet Island"}),
    "Brazil":CountryInDB(**{30:"Brazil"}),
    "British Indian Ocean Territory":CountryInDB(**{31:"British Indian Ocean Territory"}),
    "Brunei":CountryInDB(**{32:"Brunei"}),
    "Bulgaria":CountryInDB(**{33:"Bulgaria"}),
    "Burkina Faso":CountryInDB(**{34:"Burkina Faso"}),
    "Burundi":CountryInDB(**{35:"Burundi"}),
    "Cambodia":CountryInDB(**{36:"Cambodia"}),
    "Cameroon":CountryInDB(**{37:"Cameroon"}),
    "Canada":CountryInDB(**{38:"Canada"}),
    "Cape Verde":CountryInDB(**{39:"Cape Verde"}),
    "Cayman Islands":CountryInDB(**{40:"Cayman Islands"}),
    "Central African Republic":CountryInDB(**{41:"Central African Republic"}),
    "Chad":CountryInDB(**{42:"Chad"}),
    "Chile":CountryInDB(**{43:"Chile"}),
    "China":CountryInDB(**{44:"China"}),
    "Christmas Island":CountryInDB(**{45:"Christmas Island"}),
    "Cocos Keeling) Islands":CountryInDB(**{46:"Cocos Keeling) Islands"}),
    "Colombia":CountryInDB(**{47:"Colombia"}),
    "Comoros":CountryInDB(**{48:"Comoros"}),
    "Congo":CountryInDB(**{49:"Congo"}),
    "Congo":CountryInDB(**{50:"Congo"}),
    "Cook Islands":CountryInDB(**{51:"Cook Islands"}),
    "Costa Rica":CountryInDB(**{52:"Costa Rica"}),
    "Côte dIvoire":CountryInDB(**{53:"Côte dIvoire"}),
    "Croatia":CountryInDB(**{54:"Croatia"}),
    "Cuba":CountryInDB(**{55:"Cuba"}),
    "Cyprus":CountryInDB(**{56:"Cyprus"}),
    "Czech Republic":CountryInDB(**{57:"Czech Republic"}),
    "Denmark":CountryInDB(**{58:"Denmark"}),
    "Djibouti":CountryInDB(**{59:"Djibouti"}),
    "Dominica":CountryInDB(**{60:"Dominica"}),
    "Dominican Republic":CountryInDB(**{61:"Dominican Republic"}),
    "East Timor":CountryInDB(**{62:"East Timor"}),
    "Ecuador":CountryInDB(**{63:"Ecuador"}),
    "Egypt":CountryInDB(**{64:"Egypt"}),
    "El Salvador":CountryInDB(**{65:"El Salvador"}),
    "Equatorial Guinea":CountryInDB(**{66:"Equatorial Guinea"}),
    "Eritrea":CountryInDB(**{67:"Eritrea"}),
    "Estonia":CountryInDB(**{68:"Estonia"}),
    "Ethiopia":CountryInDB(**{69:"Ethiopia"}),
    "Falkland Islands":CountryInDB(**{70:"Falkland Islands"}),
    "Faroe Islands":CountryInDB(**{71:"Faroe Islands"}),
    "Fiji Islands":CountryInDB(**{72:"Fiji Islands"}),
    "Finland":CountryInDB(**{73:"Finland"}),
    "France":CountryInDB(**{74:"France"}),
    "French Guiana":CountryInDB(**{75:"French Guiana"}),
    "French Polynesia":CountryInDB(**{76:"French Polynesia"}),
    "French Southern territories":CountryInDB(**{77:"French Southern territories"}),
    "Gabon":CountryInDB(**{78:"Gabon"}),
    "Gambia":CountryInDB(**{79:"Gambia"}),
    "Georgia":CountryInDB(**{80:"Georgia"}),
    "Germany":CountryInDB(**{81:"Germany"}),
    "Ghana":CountryInDB(**{82:"Ghana"}),
    "Gibraltar":CountryInDB(**{83:"Gibraltar"}),
    "Greece":CountryInDB(**{84:"Greece"}),
    "Greenland":CountryInDB(**{85:"Greenland"}),
    "Grenada":CountryInDB(**{86:"Grenada"}),
    "Guadeloupe":CountryInDB(**{87:"Guadeloupe"}),
    "Guam":CountryInDB(**{88:"Guam"}),
    "Guatemala":CountryInDB(**{89:"Guatemala"}),
    "Guinea":CountryInDB(**{90:"Guinea"}),
    "Guinea-Bissau":CountryInDB(**{91:"Guinea-Bissau"}),
    "Guyana":CountryInDB(**{92:"Guyana"}),
    "Haiti":CountryInDB(**{93:"Haiti"}),
    "Heard Island and McDonald Islands":CountryInDB(**{94:"Heard Island and McDonald Islands"}),
    "Holy See Vatican City State)":CountryInDB(**{95:"Holy See Vatican City State)"}),
    "Honduras":CountryInDB(**{96:"Honduras"}),
    "Hong Kong":CountryInDB(**{97:"Hong Kong"}),
    "Hungary":CountryInDB(**{98:"Hungary"}),
    "Iceland":CountryInDB(**{99:"Iceland"}),
    "India":CountryInDB(**{100:"India"}),
    "Indonesia":CountryInDB(**{101:"Indonesia"}),
    "Iran":CountryInDB(**{102:"Iran"}),
    "Iraq":CountryInDB(**{103:"Iraq"}),
    "Ireland":CountryInDB(**{104:"Ireland"}),
    "Israel":CountryInDB(**{105:"Israel"}),
    "Italy":CountryInDB(**{106:"Italy"}),
    "Jamaica":CountryInDB(**{107:"Jamaica"}),
    "Japan":CountryInDB(**{108:"Japan"}),
    "Jordan":CountryInDB(**{109:"Jordan"}),
    "Kazakstan":CountryInDB(**{110:"Kazakstan"}),
    "Kenya":CountryInDB(**{111:"Kenya"}),
    "Kiribati":CountryInDB(**{112:"Kiribati"}),
    "Kuwait":CountryInDB(**{113:"Kuwait"}),
    "Kyrgyzstan":CountryInDB(**{114:"Kyrgyzstan"}),
    "Laos":CountryInDB(**{115:"Laos"}),
    "Latvia":CountryInDB(**{116:"Latvia"}),
    "Lebanon":CountryInDB(**{117:"Lebanon"}),
    "Lesotho":CountryInDB(**{118:"Lesotho"}),
    "Liberia":CountryInDB(**{119:"Liberia"}),
    "Libyan Arab Jamahiriya":CountryInDB(**{120:"Libyan Arab Jamahiriya"}),
    "Liechtenstein":CountryInDB(**{121:"Liechtenstein"}),
    "Lithuania":CountryInDB(**{122:"Lithuania"}),
    "Luxembourg":CountryInDB(**{123:"Luxembourg"}),
    "Macao":CountryInDB(**{124:"Macao"}),
    "Macedonia":CountryInDB(**{125:"Macedonia"}),
    "Madagascar":CountryInDB(**{126:"Madagascar"}),
    "Malawi":CountryInDB(**{127:"Malawi"}),
    "Malaysia":CountryInDB(**{128:"Malaysia"}),
    "Maldives":CountryInDB(**{129:"Maldives"}),
    "Mali":CountryInDB(**{130:"Mali"}),
    "Malta":CountryInDB(**{131:"Malta"}),
    "Marshall Islands":CountryInDB(**{132:"Marshall Islands"}),
    "Martinique":CountryInDB(**{133:"Martinique"}),
    "Mauritania":CountryInDB(**{134:"Mauritania"}),
    "Mauritius":CountryInDB(**{135:"Mauritius"}),
    "Mayotte":CountryInDB(**{136:"Mayotte"}),
    "Mexico":CountryInDB(**{137:"Mexico"}),
    "Micronesia":CountryInDB(**{138:"Micronesia"}),
    "Moldova":CountryInDB(**{139:"Moldova"}),
    "Monaco":CountryInDB(**{140:"Monaco"}),
    "Mongolia":CountryInDB(**{141:"Mongolia"}),
    "Montserrat":CountryInDB(**{142:"Montserrat"}),
    "Morocco":CountryInDB(**{143:"Morocco"}),
    "Mozambique":CountryInDB(**{144:"Mozambique"}),
    "Myanmar":CountryInDB(**{145:"Myanmar"}),
    "Namibia":CountryInDB(**{146:"Namibia"}),
    "Nauru":CountryInDB(**{147:"Nauru"}),
    "Nepal":CountryInDB(**{148:"Nepal"}),
    "Netherlands":CountryInDB(**{149:"Netherlands"}),
    "Netherlands Antilles":CountryInDB(**{150:"Netherlands Antilles"}),
    "New Caledonia":CountryInDB(**{151:"New Caledonia"}),
    "New Zealand":CountryInDB(**{152:"New Zealand"}),
    "Nicaragua":CountryInDB(**{153:"Nicaragua"}),
    "Niger":CountryInDB(**{154:"Niger"}),
    "Nigeria":CountryInDB(**{155:"Nigeria"}),
    "Niue":CountryInDB(**{156:"Niue"}),
    "Norfolk Island":CountryInDB(**{157:"Norfolk Island"}),
    "North Korea":CountryInDB(**{158:"North Korea"}),
    "Northern Mariana Islands":CountryInDB(**{159:"Northern Mariana Islands"}),
    "Norway":CountryInDB(**{160:"Norway"}),
    "Oman":CountryInDB(**{161:"Oman"}),
    "Pakistan":CountryInDB(**{162:"Pakistan"}),
    "Palau":CountryInDB(**{163:"Palau"}),
    "Palestine":CountryInDB(**{164:"Palestine"}),
    "Panama":CountryInDB(**{165:"Panama"}),
    "Papua New Guinea":CountryInDB(**{166:"Papua New Guinea"}),
    "Paraguay":CountryInDB(**{167:"Paraguay"}),
    "Peru":CountryInDB(**{168:"Peru"}),
    "Philippines":CountryInDB(**{169:"Philippines"}),
    "Pitcairn":CountryInDB(**{170:"Pitcairn"}),
    "Poland":CountryInDB(**{171:"Poland"}),
    "Portugal":CountryInDB(**{172:"Portugal"}),
    "Puerto Rico":CountryInDB(**{173:"Puerto Rico"}),
    "Qatar":CountryInDB(**{174:"Qatar"}),
    "Réunion":CountryInDB(**{175:"Réunion"}),
    "Romania":CountryInDB(**{176:"Romania"}),
    "Russian Federation":CountryInDB(**{177:"Russian Federation"}),
    "Rwanda":CountryInDB(**{178:"Rwanda"}),
    "Saint Helena":CountryInDB(**{179:"Saint Helena"}),
    "Saint Kitts and Nevis":CountryInDB(**{180:"Saint Kitts and Nevis"}),
    "Saint Lucia":CountryInDB(**{181:"Saint Lucia"}),
    "Saint Pierre and Miquelon":CountryInDB(**{182:"Saint Pierre and Miquelon"}),
    "Saint Vincent and the Grenadines":CountryInDB(**{183:"Saint Vincent and the Grenadines"}),
    "Samoa":CountryInDB(**{184:"Samoa"}),
    "San Marino":CountryInDB(**{185:"San Marino"}),
    "Sao Tome and Principe":CountryInDB(**{186:"Sao Tome and Principe"}),
    "Saudi Arabia":CountryInDB(**{187:"Saudi Arabia"}),
    "Senegal":CountryInDB(**{188:"Senegal"}),
    "Seychelles":CountryInDB(**{189:"Seychelles"}),
    "Sierra Leone":CountryInDB(**{190:"Sierra Leone"}),
    "Singapore":CountryInDB(**{191:"Singapore"}),
    "Slovakia":CountryInDB(**{192:"Slovakia"}),
    "Slovenia":CountryInDB(**{193:"Slovenia"}),
    "Solomon Islands":CountryInDB(**{194:"Solomon Islands"}),
    "Somalia":CountryInDB(**{195:"Somalia"}),
    "South Africa":CountryInDB(**{196:"South Africa"}),
    "South Georgia and the South Sandwich Islands":CountryInDB(**{197:"South Georgia and the South Sandwich Islands"}),
    "South Korea":CountryInDB(**{198:"South Korea"}),
    "Spain":CountryInDB(**{199:"Spain"}),
    "Sri Lanka":CountryInDB(**{200:"Sri Lanka"}),
    "Sudan":CountryInDB(**{201:"Sudan"}),
    "Suriname":CountryInDB(**{202:"Suriname"}),
    "Svalbard and Jan Mayen":CountryInDB(**{203:"Svalbard and Jan Mayen"}),
    "Swaziland":CountryInDB(**{204:"Swaziland"}),
    "Sweden":CountryInDB(**{205:"Sweden"}),
    "Switzerland":CountryInDB(**{206:"Switzerland"}),
    "Syria":CountryInDB(**{207:"Syria"}),
    "Taiwan":CountryInDB(**{208:"Taiwan"}),
    "Tajikistan":CountryInDB(**{209:"Tajikistan"}),
    "Tanzania":CountryInDB(**{210:"Tanzania"}),
    "Thailand":CountryInDB(**{211:"Thailand"}),
    "Togo":CountryInDB(**{212:"Togo"}),
    "Tokelau":CountryInDB(**{213:"Tokelau"}),
    "Tonga":CountryInDB(**{214:"Tonga"}),
    "Trinidad and Tobago":CountryInDB(**{215:"Trinidad and Tobago"}),
    "Tunisia":CountryInDB(**{216:"Tunisia"}),
    "Turkey":CountryInDB(**{217:"Turkey"}),
    "Turkmenistan":CountryInDB(**{218:"Turkmenistan"}),
    "Turks and Caicos Islands":CountryInDB(**{219:"Turks and Caicos Islands"}),
    "Tuvalu":CountryInDB(**{220:"Tuvalu"}),
    "Uganda":CountryInDB(**{221:"Uganda"}),
    "Ukraine":CountryInDB(**{222:"Ukraine"}),
    "United Arab Emirates":CountryInDB(**{223:"United Arab Emirates"}),
    "United Kingdom":CountryInDB(**{224:"United Kingdom"}),
    "United States":CountryInDB(**{225:"United States"}),
    "United States Minor Outlying Islands":CountryInDB(**{226:"United States Minor Outlying Islands"}),
    "Uruguay":CountryInDB(**{227:"Uruguay"}),
    "Uzbekistan":CountryInDB(**{228:"Uzbekistan"}),
    "Vanuatu":CountryInDB(**{229:"Vanuatu"}),
    "Venezuela":CountryInDB(**{230:"Venezuela"}),
    "Vietnam":CountryInDB(**{231:"Vietnam"}),
    "Virgin Islands":CountryInDB(**{232:"Virgin Islands"}),
    "Virgin Islands":CountryInDB(**{233:"Virgin Islands"}),
    "Wallis and Futuna":CountryInDB(**{234:"Wallis and Futuna"}),
    "Western Sahara":CountryInDB(**{235:"Western Sahara"}),
    "Yemen":CountryInDB(**{236:"Yemen"}),
    "Yugoslavia":CountryInDB(**{237:"Yugoslavia"}),
    "Zambia":CountryInDB(**{238:"Zambia"}),
    "Zimbabwe":CountryInDB(**{239:"Zimbabwe"})
}

def get_id(name:str):
    if name in database_country_name.keys():
        return database_country_name[name]
    else:
        return None

def get_name(id:int):
    if id in database_country.keys():
        return database_country[id]
    else:
        return None
